# This is a basic workflow to help you get started with Actions

name: 🚀 Build & Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: dulliag.de
          username: ftp_thorben
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./docs.dulliag.de/build/
